// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmwtiqhowrconndntekz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1td3RpcWhvd3Jjb25uZG50ZWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTgwNTksImV4cCI6MjA3Mzc3NDA1OX0.yhkBJ4ddRUqX0afPZTy7tAnedDKgL7EBcXYHD-TwbHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});